import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/navbar";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oswald.variable} ${oswald.variable} font-oswald tracking-wide antialiased flex flex-col items-center justify-center min-w-screen max-w-screen overflow-x-hidden`}
      >
        <Navigation />
        <div className="flex w-full flex-1 flex-col items-center justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}
